Update extract_frames.py
python extract_frames.py                                                    
Traceback (most recent call last):
  File "/home/relh/Code/AURORA/data/something/extract_frames.py", line 58, in <module>
    with open(json_file, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'validation_2K.json'


This file doesn't exist however you have one called `valid.json` and changing the path here seems to fix extract_frames.py